name: Build and Push Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./deploy/Dockerfile
        push: true
        tags: |
          ghcr.io/medusa-ml/translatetribune:latest
          ghcr.io/medusa-ml/translatetribune:${{ github.sha }}

